/* Generated By:JJTree: Do not edit this line. ASTDeclaratorNonInit.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.unipe.m2asm.parse;

public
@SuppressWarnings("all")
class ASTDeclaratorNonInit extends M2AsmNode {
  public ASTDeclaratorNonInit(int id) {
    super(id);
  }

  public ASTDeclaratorNonInit(M2AsmParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(M2AsmParserVisitor visitor, br.unipe.m2asm.codegen.SymbolTable data) {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1a908a8bc6d5ab4d4c140717c63e9e7d (do not edit this line) */
