/* Generated By:JavaCC: Do not edit this line. M2AsmParserVisitor.java Version 5.0 */
package br.unipe.m2asm.parse;

@SuppressWarnings("all")
public interface M2AsmParserVisitor
{
  public void visit(SimpleNode node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTProg node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTSegment node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTStackDecl node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTStmt node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTPseudoStmt node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTInclude node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTDef node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTMacro node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTOpcode node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTDeclarator node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTDeclaratorNonInit node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTValues node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTLabel node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTId node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTInteger node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTChar node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTStr node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTRegInt node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTRegFloat node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTMemRef node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTMemOffset node, br.unipe.m2asm.codegen.SymbolTable data);
  public void visit(ASTMemSize node, br.unipe.m2asm.codegen.SymbolTable data);
}
/* JavaCC - OriginalChecksum=26fdb20a52602e73af97e874e2378f9d (do not edit this line) */
