/* Generated By:JJTree&JavaCC: Do not edit this line. M2AsmParserTokenManager.java */
package br.unipe.m2asm.parse;

/** Token Manager. */
@SuppressWarnings("all")
public class M2AsmParserTokenManager implements M2AsmParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 40:
         return jjStopAtPos(0, 62);
      case 41:
         return jjStopAtPos(0, 63);
      case 42:
         return jjStopAtPos(0, 61);
      case 43:
         return jjStopAtPos(0, 64);
      case 44:
         return jjStopAtPos(0, 59);
      case 45:
         return jjStartNfaWithStates_0(0, 65, 1);
      case 58:
         return jjStopAtPos(0, 60);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 291;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 3)
                        kind = 3;
                     jjCheckNAddTwoStates(2, 3);
                  }
                  else if ((0x2400L & l) != 0L)
                  {
                     if (kind > 9)
                        kind = 9;
                  }
                  else if (curChar == 37)
                     jjAddStates(0, 13);
                  else if (curChar == 48)
                  {
                     if (kind > 3)
                        kind = 3;
                     jjCheckNAddStates(14, 16);
                  }
                  else if (curChar == 46)
                  {
                     if (kind > 55)
                        kind = 55;
                     jjCheckNAdd(60);
                  }
                  else if (curChar == 59)
                     jjCheckNAddTwoStates(11, 12);
                  else if (curChar == 34)
                     jjCheckNAddTwoStates(8, 9);
                  else if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 5;
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 1;
                  if (curChar == 10)
                     jjstateSet[jjnewStateCnt++] = 15;
                  else if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 1:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAddTwoStates(2, 3);
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAddTwoStates(2, 3);
                  break;
               case 4:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 5:
                  jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 6:
                  if (curChar == 39 && kind > 7)
                     kind = 7;
                  break;
               case 7:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(8, 9);
                  break;
               case 8:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(8, 9);
                  break;
               case 9:
                  if (curChar == 34 && kind > 8)
                     kind = 8;
                  break;
               case 10:
                  if (curChar == 59)
                     jjCheckNAddTwoStates(11, 12);
                  break;
               case 11:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddTwoStates(11, 12);
                  break;
               case 12:
                  if ((0x2400L & l) != 0L && kind > 9)
                     kind = 9;
                  break;
               case 13:
                  if (curChar == 10 && kind > 9)
                     kind = 9;
                  break;
               case 14:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (curChar == 13 && kind > 9)
                     kind = 9;
                  break;
               case 16:
                  if (curChar == 10)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) != 0L && kind > 53)
                     kind = 53;
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 54)
                     kind = 54;
                  jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 58:
                  if ((0x3ff000000000000L & l) != 0L && kind > 54)
                     kind = 54;
                  break;
               case 59:
                  if (curChar != 46)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAdd(60);
                  break;
               case 60:
                  if ((0x3ff400000000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAdd(60);
                  break;
               case 67:
                  if (curChar != 48)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAddStates(14, 16);
                  break;
               case 69:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAddTwoStates(69, 3);
                  break;
               case 70:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAddTwoStates(70, 3);
                  break;
               case 218:
                  if (curChar == 37)
                     jjAddStates(0, 13);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 55)
                        kind = 55;
                     jjCheckNAdd(60);
                  }
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  else if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 50;
                  else if (curChar == 112)
                     jjAddStates(17, 18);
                  else if (curChar == 80)
                     jjAddStates(19, 20);
                  else if (curChar == 106)
                     jjAddStates(21, 27);
                  else if (curChar == 74)
                     jjAddStates(28, 34);
                  else if (curChar == 99)
                     jjAddStates(35, 37);
                  else if (curChar == 67)
                     jjAddStates(38, 40);
                  else if (curChar == 110)
                     jjAddStates(41, 42);
                  else if (curChar == 78)
                     jjAddStates(43, 46);
                  else if (curChar == 109)
                     jjCheckNAddTwoStates(134, 63);
                  else if (curChar == 77)
                     jjCheckNAddTwoStates(131, 66);
                  else if (curChar == 115)
                     jjCheckNAddStates(47, 53);
                  else if (curChar == 83)
                     jjCheckNAddStates(54, 60);
                  else if (curChar == 97)
                     jjAddStates(61, 62);
                  else if (curChar == 65)
                     jjAddStates(63, 64);
                  else if (curChar == 100)
                     jjCheckNAddStates(65, 69);
                  else if (curChar == 68)
                     jjCheckNAddStates(70, 74);
                  else if (curChar == 105)
                     jjCheckNAddStates(75, 78);
                  else if (curChar == 73)
                     jjCheckNAddStates(79, 82);
                  else if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 54;
                  else if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 52;
                  else if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 47;
                  else if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 43;
                  else if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 39;
                  else if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 36;
                  else if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 33;
                  else if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 30;
                  else if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 27;
                  else if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 25;
                  else if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 23;
                  else if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 19;
                  if (curChar == 114)
                     jjAddStates(83, 85);
                  else if (curChar == 82)
                     jjAddStates(86, 88);
                  else if (curChar == 70)
                     jjCheckNAddTwoStates(65, 66);
                  else if (curChar == 102)
                     jjCheckNAddTwoStates(62, 63);
                  break;
               case 3:
                  if ((0x100000001000L & l) != 0L && kind > 3)
                     kind = 3;
                  break;
               case 5:
                  jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  jjAddStates(89, 90);
                  break;
               case 11:
                  jjAddStates(91, 92);
                  break;
               case 17:
                  if (curChar == 84 && kind > 11)
                     kind = 11;
                  break;
               case 18:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 116 && kind > 11)
                     kind = 11;
                  break;
               case 22:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 23:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
                  if (curChar == 82 && kind > 20)
                     kind = 20;
                  break;
               case 26:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 114 && kind > 20)
                     kind = 20;
                  break;
               case 28:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 29:
                  if (curChar == 82 && kind > 21)
                     kind = 21;
                  break;
               case 30:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if (curChar == 114 && kind > 21)
                     kind = 21;
                  break;
               case 33:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 34:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 35:
                  if (curChar == 68 && kind > 27)
                     kind = 27;
                  break;
               case 36:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
                  if (curChar == 100 && kind > 27)
                     kind = 27;
                  break;
               case 39:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 41:
                  if (curChar == 69 && kind > 52)
                     kind = 52;
                  break;
               case 42:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 43:
                  if (curChar == 89)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 44:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 45:
                  if (curChar == 101 && kind > 52)
                     kind = 52;
                  break;
               case 46:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 47:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 48:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 49:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 52:
                  if (curChar == 100 && kind > 53)
                     kind = 53;
                  break;
               case 53:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 54:
                  if (curChar == 68 && kind > 53)
                     kind = 53;
                  break;
               case 55:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 59:
               case 60:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAdd(60);
                  break;
               case 61:
                  if (curChar == 102)
                     jjCheckNAddTwoStates(62, 63);
                  break;
               case 62:
                  if (curChar == 112 && kind > 53)
                     kind = 53;
                  break;
               case 63:
                  if (curChar == 114 && kind > 53)
                     kind = 53;
                  break;
               case 64:
                  if (curChar == 70)
                     jjCheckNAddTwoStates(65, 66);
                  break;
               case 65:
                  if (curChar == 80 && kind > 53)
                     kind = 53;
                  break;
               case 66:
                  if (curChar == 82 && kind > 53)
                     kind = 53;
                  break;
               case 68:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(69);
                  break;
               case 69:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAddTwoStates(69, 3);
                  break;
               case 71:
                  if (curChar == 73)
                     jjCheckNAddStates(79, 82);
                  break;
               case 72:
                  if (curChar == 67 && kind > 12)
                     kind = 12;
                  break;
               case 73:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 74:
                  if (curChar == 84 && kind > 36)
                     kind = 36;
                  break;
               case 75:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 76:
                  if (curChar == 105)
                     jjCheckNAddStates(75, 78);
                  break;
               case 77:
                  if (curChar == 99 && kind > 12)
                     kind = 12;
                  break;
               case 78:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 79:
                  if (curChar == 116 && kind > 36)
                     kind = 36;
                  break;
               case 80:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 68)
                     jjCheckNAddStates(70, 74);
                  break;
               case 82:
                  if (curChar == 67 && kind > 13)
                     kind = 13;
                  break;
               case 83:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 84:
                  if (curChar == 86 && kind > 17)
                     kind = 17;
                  break;
               case 85:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 86:
                  if (curChar == 66 && kind > 48)
                     kind = 48;
                  break;
               case 87:
                  if (curChar == 87 && kind > 49)
                     kind = 49;
                  break;
               case 88:
                  if (curChar == 84 && kind > 53)
                     kind = 53;
                  break;
               case 89:
                  if (curChar == 100)
                     jjCheckNAddStates(65, 69);
                  break;
               case 90:
                  if (curChar == 99 && kind > 13)
                     kind = 13;
                  break;
               case 91:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 92:
                  if (curChar == 118 && kind > 17)
                     kind = 17;
                  break;
               case 93:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 94:
                  if (curChar == 98 && kind > 48)
                     kind = 48;
                  break;
               case 95:
                  if (curChar == 119 && kind > 49)
                     kind = 49;
                  break;
               case 96:
                  if (curChar == 116 && kind > 53)
                     kind = 53;
                  break;
               case 97:
                  if (curChar == 65)
                     jjAddStates(63, 64);
                  break;
               case 98:
                  if (curChar == 68 && kind > 14)
                     kind = 14;
                  break;
               case 99:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if (curChar == 68 && kind > 19)
                     kind = 19;
                  break;
               case 101:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if (curChar == 97)
                     jjAddStates(61, 62);
                  break;
               case 103:
                  if (curChar == 100 && kind > 14)
                     kind = 14;
                  break;
               case 104:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 105:
                  if (curChar == 100 && kind > 19)
                     kind = 19;
                  break;
               case 106:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if (curChar == 83)
                     jjCheckNAddStates(54, 60);
                  break;
               case 108:
                  if (curChar == 66 && kind > 15)
                     kind = 15;
                  break;
               case 109:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 110:
                  if (curChar == 76 && kind > 23)
                     kind = 23;
                  break;
               case 111:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 112:
                  if (curChar == 82 && kind > 24)
                     kind = 24;
                  break;
               case 113:
                  if (curChar == 72)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 114:
                  if (curChar == 82 && kind > 28)
                     kind = 28;
                  break;
               case 115:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 116:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 117:
                  if (curChar == 66 && kind > 53)
                     kind = 53;
                  break;
               case 118:
                  if (curChar == 115)
                     jjCheckNAddStates(47, 53);
                  break;
               case 119:
                  if (curChar == 98 && kind > 15)
                     kind = 15;
                  break;
               case 120:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 121:
                  if (curChar == 108 && kind > 23)
                     kind = 23;
                  break;
               case 122:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 123:
                  if (curChar == 114 && kind > 24)
                     kind = 24;
                  break;
               case 124:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 125:
                  if (curChar == 114 && kind > 28)
                     kind = 28;
                  break;
               case 126:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 127:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 98 && kind > 53)
                     kind = 53;
                  break;
               case 129:
                  if (curChar == 77)
                     jjCheckNAddTwoStates(131, 66);
                  break;
               case 130:
                  if (curChar == 76 && kind > 16)
                     kind = 16;
                  break;
               case 131:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 132:
                  if (curChar == 109)
                     jjCheckNAddTwoStates(134, 63);
                  break;
               case 133:
                  if (curChar == 108 && kind > 16)
                     kind = 16;
                  break;
               case 134:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 135:
                  if (curChar == 78)
                     jjAddStates(43, 46);
                  break;
               case 136:
                  if (curChar == 80 && kind > 10)
                     kind = 10;
                  break;
               case 137:
               case 138:
                  if (curChar == 79)
                     jjCheckNAdd(136);
                  break;
               case 139:
                  if (curChar == 71 && kind > 18)
                     kind = 18;
                  break;
               case 140:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 141:
                  if (curChar == 84 && kind > 22)
                     kind = 22;
                  break;
               case 142:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 143:
                  if (curChar == 110)
                     jjAddStates(41, 42);
                  break;
               case 144:
                  if (curChar == 103 && kind > 18)
                     kind = 18;
                  break;
               case 145:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 146:
                  if (curChar == 116 && kind > 22)
                     kind = 22;
                  break;
               case 147:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 146;
                  break;
               case 148:
                  if (curChar == 67)
                     jjAddStates(38, 40);
                  break;
               case 149:
                  if (curChar == 89 && kind > 25)
                     kind = 25;
                  break;
               case 150:
                  if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 151:
                  if (curChar == 80 && kind > 26)
                     kind = 26;
                  break;
               case 152:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 153:
                  if (curChar == 76 && kind > 37)
                     kind = 37;
                  break;
               case 154:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 155:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 156:
                  if (curChar == 99)
                     jjAddStates(35, 37);
                  break;
               case 157:
                  if (curChar == 121 && kind > 25)
                     kind = 25;
                  break;
               case 158:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 159:
                  if (curChar == 112 && kind > 26)
                     kind = 26;
                  break;
               case 160:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 159;
                  break;
               case 161:
                  if (curChar == 108 && kind > 37)
                     kind = 37;
                  break;
               case 162:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 163:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 164:
                  if (curChar == 74)
                     jjAddStates(28, 34);
                  break;
               case 165:
                  if (curChar == 80 && kind > 29)
                     kind = 29;
                  break;
               case 166:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 167:
                  if (curChar == 69 && kind > 30)
                     kind = 30;
                  break;
               case 168:
                  if (curChar == 69 && kind > 31)
                     kind = 31;
                  break;
               case 169:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 170:
                  if (curChar == 76 && kind > 32)
                     kind = 32;
                  break;
               case 171:
                  if (curChar == 69 && kind > 33)
                     kind = 33;
                  break;
               case 172:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 173:
                  if (curChar == 71 && kind > 34)
                     kind = 34;
                  break;
               case 174:
                  if (curChar == 69 && kind > 35)
                     kind = 35;
                  break;
               case 175:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 176:
                  if (curChar == 106)
                     jjAddStates(21, 27);
                  break;
               case 177:
                  if (curChar == 112 && kind > 29)
                     kind = 29;
                  break;
               case 178:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 177;
                  break;
               case 179:
                  if (curChar == 101 && kind > 30)
                     kind = 30;
                  break;
               case 180:
                  if (curChar == 101 && kind > 31)
                     kind = 31;
                  break;
               case 181:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 180;
                  break;
               case 182:
                  if (curChar == 108 && kind > 32)
                     kind = 32;
                  break;
               case 183:
                  if (curChar == 101 && kind > 33)
                     kind = 33;
                  break;
               case 184:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 185:
                  if (curChar == 103 && kind > 34)
                     kind = 34;
                  break;
               case 186:
                  if (curChar == 101 && kind > 35)
                     kind = 35;
                  break;
               case 187:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 186;
                  break;
               case 188:
                  if (curChar == 82)
                     jjAddStates(86, 88);
                  break;
               case 189:
                  if (curChar == 84 && kind > 38)
                     kind = 38;
                  break;
               case 190:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 189;
                  break;
               case 191:
                  if (curChar == 66 && kind > 50)
                     kind = 50;
                  break;
               case 192:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 191;
                  break;
               case 193:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 192;
                  break;
               case 194:
                  if (curChar == 87 && kind > 51)
                     kind = 51;
                  break;
               case 195:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 196:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 197:
                  if (curChar == 114)
                     jjAddStates(83, 85);
                  break;
               case 198:
                  if (curChar == 116 && kind > 38)
                     kind = 38;
                  break;
               case 199:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 198;
                  break;
               case 200:
                  if (curChar == 98 && kind > 50)
                     kind = 50;
                  break;
               case 201:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 200;
                  break;
               case 202:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 203:
                  if (curChar == 119 && kind > 51)
                     kind = 51;
                  break;
               case 204:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 203;
                  break;
               case 205:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 204;
                  break;
               case 206:
                  if (curChar == 80)
                     jjAddStates(19, 20);
                  break;
               case 207:
                  if (curChar == 72 && kind > 39)
                     kind = 39;
                  break;
               case 208:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 209:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 208;
                  break;
               case 210:
                  if (curChar == 80 && kind > 40)
                     kind = 40;
                  break;
               case 211:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 210;
                  break;
               case 212:
                  if (curChar == 112)
                     jjAddStates(17, 18);
                  break;
               case 213:
                  if (curChar == 104 && kind > 39)
                     kind = 39;
                  break;
               case 214:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 213;
                  break;
               case 215:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 214;
                  break;
               case 216:
                  if (curChar == 112 && kind > 40)
                     kind = 40;
                  break;
               case 217:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 216;
                  break;
               case 219:
                  if (curChar == 69 && kind > 41)
                     kind = 41;
                  break;
               case 220:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 219;
                  break;
               case 221:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 220;
                  break;
               case 222:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 223:
                  if (curChar == 101 && kind > 41)
                     kind = 41;
                  break;
               case 224:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 223;
                  break;
               case 225:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 224;
                  break;
               case 226:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 225;
                  break;
               case 227:
                  if (curChar == 65 && kind > 42)
                     kind = 42;
                  break;
               case 228:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 227;
                  break;
               case 229:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 228;
                  break;
               case 230:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 229;
                  break;
               case 231:
                  if (curChar == 97 && kind > 42)
                     kind = 42;
                  break;
               case 232:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 231;
                  break;
               case 233:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 232;
                  break;
               case 234:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 235:
                  if (curChar == 75 && kind > 43)
                     kind = 43;
                  break;
               case 236:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 237:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 238:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 237;
                  break;
               case 239:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 238;
                  break;
               case 240:
                  if (curChar == 107 && kind > 43)
                     kind = 43;
                  break;
               case 241:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 240;
                  break;
               case 242:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 241;
                  break;
               case 243:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 244:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 243;
                  break;
               case 245:
                  if (curChar == 69 && kind > 44)
                     kind = 44;
                  break;
               case 246:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 245;
                  break;
               case 247:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 246;
                  break;
               case 248:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 247;
                  break;
               case 249:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 248;
                  break;
               case 250:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 249;
                  break;
               case 251:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 250;
                  break;
               case 252:
                  if (curChar == 101 && kind > 44)
                     kind = 44;
                  break;
               case 253:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 252;
                  break;
               case 254:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 253;
                  break;
               case 255:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 254;
                  break;
               case 256:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 255;
                  break;
               case 257:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 256;
                  break;
               case 258:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 257;
                  break;
               case 259:
                  if (curChar == 70 && kind > 45)
                     kind = 45;
                  break;
               case 260:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 259;
                  break;
               case 261:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 260;
                  break;
               case 262:
                  if (curChar == 102 && kind > 45)
                     kind = 45;
                  break;
               case 263:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 262;
                  break;
               case 264:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 263;
                  break;
               case 265:
                  if (curChar == 79 && kind > 46)
                     kind = 46;
                  break;
               case 266:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 265;
                  break;
               case 267:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 266;
                  break;
               case 268:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 267;
                  break;
               case 269:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 270:
                  if (curChar == 111 && kind > 46)
                     kind = 46;
                  break;
               case 271:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 270;
                  break;
               case 272:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 271;
                  break;
               case 273:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 272;
                  break;
               case 274:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 273;
                  break;
               case 275:
                  if (curChar == 79 && kind > 47)
                     kind = 47;
                  break;
               case 276:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 275;
                  break;
               case 277:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 276;
                  break;
               case 278:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 277;
                  break;
               case 279:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 278;
                  break;
               case 280:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 279;
                  break;
               case 281:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 280;
                  break;
               case 282:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 281;
                  break;
               case 283:
                  if (curChar == 111 && kind > 47)
                     kind = 47;
                  break;
               case 284:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 283;
                  break;
               case 285:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 284;
                  break;
               case 286:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 285;
                  break;
               case 287:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 286;
                  break;
               case 288:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 287;
                  break;
               case 289:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 288;
                  break;
               case 290:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 289;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 5:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(89, 90);
                  break;
               case 11:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(91, 92);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 291 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   222, 226, 230, 234, 239, 244, 251, 258, 261, 264, 269, 274, 282, 290, 68, 70, 
   3, 215, 217, 209, 211, 178, 179, 181, 182, 184, 185, 187, 166, 167, 169, 170, 
   172, 173, 175, 158, 160, 163, 150, 152, 155, 145, 147, 137, 138, 140, 142, 120, 
   122, 124, 127, 62, 128, 96, 109, 111, 113, 116, 65, 117, 88, 104, 106, 99, 
   101, 91, 93, 94, 95, 96, 83, 85, 86, 87, 88, 78, 80, 62, 63, 73, 
   75, 65, 66, 199, 202, 205, 190, 193, 196, 8, 9, 11, 12, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, "\54", "\72", "\52", "\50", "\51", "\53", "\55", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xf8ffffffffffff89L, 0x3L, 
};
static final long[] jjtoSkip = {
   0x6L, 0x0L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[291];
private final int[] jjstateSet = new int[582];
protected char curChar;
/** Constructor. */
public M2AsmParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public M2AsmParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 291; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100000200L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
