/* Generated By:JavaCC: Do not edit this line. M2AsmParserTreeConstants.java Version 5.0 */
package br.unipe.m2asm.parse;

@SuppressWarnings("all")
public interface M2AsmParserTreeConstants
{
  public int JJTPROG = 0;
  public int JJTSEGMENT = 1;
  public int JJTSTACKDECL = 2;
  public int JJTVOID = 3;
  public int JJTSTMT = 4;
  public int JJTPSEUDOSTMT = 5;
  public int JJTINCLUDE = 6;
  public int JJTDEF = 7;
  public int JJTMACRO = 8;
  public int JJTOPCODE = 9;
  public int JJTDECLARATOR = 10;
  public int JJTDECLARATORNONINIT = 11;
  public int JJTVALUES = 12;
  public int JJTLABEL = 13;
  public int JJTID = 14;
  public int JJTINTEGER = 15;
  public int JJTCHAR = 16;
  public int JJTSTR = 17;
  public int JJTREGINT = 18;
  public int JJTREGFLOAT = 19;
  public int JJTMEMREF = 20;
  public int JJTMEMOFFSET = 21;
  public int JJTMEMSIZE = 22;


  public String[] jjtNodeName = {
    "Prog",
    "Segment",
    "StackDecl",
    "void",
    "Stmt",
    "PseudoStmt",
    "Include",
    "Def",
    "Macro",
    "Opcode",
    "Declarator",
    "DeclaratorNonInit",
    "Values",
    "Label",
    "Id",
    "Integer",
    "Char",
    "Str",
    "RegInt",
    "RegFloat",
    "MemRef",
    "MemOffset",
    "MemSize",
  };
}
/* JavaCC - OriginalChecksum=2a5bc977df4aff6768c8392c2a985080 (do not edit this line) */
